% Write site locations and connectivity matrix, with associated metadata,
% to a NetCDF file for uploading to THREDDS server.
function writeConnectivityNC(varargin)

    narginchk(0,12);

    % 1. table of sites
    sitefile = 'C:\Users\SA01TA\Documents\Sealice_NorthMinch\site_locations\all_sites_wgs84.dat';
    sites = readtable(sitefile,'Format','%s%f%f%f%f%f%f%s%s%s');
    % 2. numeric matrix of connectivity values
    connectfile1='E:\westcoasttracking_out\minchcont\20130912_1_337_12\connect_density.dat';
    connectivity=load(connectfile1);
    % 3. dates of simulation start
    startDates=char({'20130912'});%,'2013-09-26','2014-02-20'});
    % 4. species
    species='nephrops';
    % 5. habitat configuration
    habitat='functional units';
    % 6.
    behaviour='fixedDepth24m';
    
    for i = 1:2:length(varargin) % only bother with odd arguments, i.e. the labels
        switch varargin{i}
            case 'sites'
                sites = varargin{i+1};
            case 'connectivity'
                connectivity = varargin{i+1};
            case 'startdate'
                startDates = varargin{i+1};
            case 'species'
                species = varargin{i+1};
            case 'habitat'
                habitat = varargin{i+1};
            case 'behaviour'
                behaviour = varargin{i+1};
        end
    end
    
    siteNames = char(table2cell(sites(:,1)));
    siteLon = table2array(sites(:,2));
    siteLat = table2array(sites(:,3));

    startDateTimes=datetime(startDates,'InputFormat','yyyyMMdd');
    modJulDay=juliandate(startDateTimes,'modifiedjuliandate');

    ind=1;
    connectTable=zeros(nnz(connectivity),3);
    for row=1:size(connectivity,1)
        for col=1:size(connectivity,2)
            if connectivity(row,col) > 0
                connectTable(ind,:)=[row,col,connectivity(row,col)];
                ind=ind+1;
            end
        end
    end

    % Summary values to be provided in separate tables
    nSources=sum(connectivity~=0,1);
    nDestinations=sum(connectivity~=0,2);
    sumSources=sum(connectivity,1);
    sumDestinations=sum(connectivity,2);


    ncfilename = ['connectivity_' species '_' habitat '_' behaviour '_' startDates '.nc'];

    delete(ncfilename)
    % sites
    % nccreate(ncfilename,'siteNames','Dimensions',{'elems' length(siteNames) 'one' 1},'Datatype','single');
    % ncwrite(ncfilename,'siteNames',sites(:,1))

    % int crs ;
    %     crs:grid_mapping_name = "latitude_longitude";
    %     ...
    %     crs:crs_wkt =
    %      GEODCRS["WGS 84",
    %      DATUM["World Geodetic System 1984",
    %        ELLIPSOID["WGS 84",6378137,298.257223563,
    %          LENGTHUNIT["metre",1.0]]],
    %      PRIMEM["Greenwich",0],
    %      CS[ellipsoidal,3],
    %        AXIS["(lat)",north,ANGLEUNIT["degree",0.0174532925199433]],
    %        AXIS["(lon)",east,ANGLEUNIT["degree",0.0174532925199433]],
    %        AXIS["ellipsoidal height (h)",up,LENGTHUNIT["metre",1.0]]]

    mode = bitor(netcdf.getConstant('CLOBBER'),netcdf.getConstant('64BIT_OFFSET'));
    ncid = netcdf.create(ncfilename,mode);

    globalVarId=netcdf.getConstant('GLOBAL');
    netcdf.putAtt(ncid,globalVarId,'name',ncfilename);
    netcdf.putAtt(ncid,globalVarId,'runID',[species '_' habitat '_' behaviour '_' startDates]);

    % Extra attributes requested by Paola
    netcdf.putAtt(ncid,globalVarId,'infoUrl','https://www.sams.ac.uk/science/projects/compass/');
    netcdf.putAtt(ncid,globalVarId,'institution','Scottish Association for Marine Science (sams.ac.uk)');
    netcdf.putAtt(ncid,globalVarId,'summary','Pelagic connectivity between habitat sites, generated by particle tracking on combined output grids from FVCOM and ROMS in the Irish/Scottish coastal region.');
    netcdf.putAtt(ncid,globalVarId,'title',['Habitat connectivity for species "' species '" habitat "' habitat '"']);
    netcdf.putAtt(ncid,globalVarId,'creator_email','tom.adams@sams.ac.uk');
    netcdf.putAtt(ncid,globalVarId,'creator_name','Thomas P. Adams');
    netcdf.putAtt(ncid,globalVarId,'creator_url','https://www.sams.ac.uk/people/researchers/adams-dr-thomas/');

    %netcdf.putAtt(ncid,globalVarId,'dispersalDuration','14 days');
    %netcdf.putAtt(ncid,globalVarId,'releaseDuration','1 days');
    netcdf.putAtt(ncid,globalVarId,'species',species);
    netcdf.putAtt(ncid,globalVarId,'habitatConfig',habitat);
    %netcdf.putAtt(ncid,globalVarId,'particleTrack_configFile','C:\Users\SA01TA\Documents\particle_track\sites.properties');
    %netcdf.putAtt(ncid,globalVarId,'particleTrackExecutable','C:\Users\SA01TA\Documents\particle_track\dist\particle_track.jar');
    netcdf.putAtt(ncid,globalVarId,'particleTrackRepository','https://bitbucket.org/tomadams1982/biotracker/src/master/');
    netcdf.putAtt(ncid,globalVarId,'particleTrack version','Mon Jan 14 17:32:19 2019 +0000');
    netcdf.putAtt(ncid,globalVarId,'ROMS_directory','D:\hydroOut\NEA_ROMS\');
    netcdf.putAtt(ncid,globalVarId,'ROMS_url','http://milas.marine.ie/thredds/catalog/IMI_ROMS_HYDRO/NEATLANTIC_NATIVE_2KM_40L_1H/ANALYSIS/catalog.html');
    netcdf.putAtt(ncid,globalVarId,'FVCOM_directory','D:\hydroOut\minch_FVCOM\');
    netcdf.putAtt(ncid,globalVarId,'CoordinateSystem','GeoReferenced');
    netcdf.putAtt(ncid,globalVarId,'CoordinateProjection','none');

    siteCount = netcdf.defDim(ncid,'numberOfSites',size(siteNames,1));
    nConnections = netcdf.defDim(ncid,'numberOfConnections',size(connectTable,1));
    %one = netcdf.defDim(ncid,'one',1);
    three = netcdf.defDim(ncid,'three',3);
    nameLength = netcdf.defDim(ncid,'nameLength',size(siteNames,2));
    dateLength = netcdf.defDim(ncid,'dateLength',size(startDates,2));
    %nDates = netcdf.defDim(ncid,'nDates',size(connectivity,3));
    nDates = netcdf.defDim(ncid,'nDates',1);

    IDVarId1 = netcdf.defVar(ncid,'ID','char',[siteCount nameLength]);
    netcdf.putAtt(ncid,IDVarId1,'longName','site name/identifier');
    netcdf.putAtt(ncid,IDVarId1,'units','name');

    IDVarId2 = netcdf.defVar(ncid,'lon','double',[siteCount]);
    netcdf.putAtt(ncid,IDVarId2,'standardName','longitude');
    netcdf.putAtt(ncid,IDVarId2,'longName','longitude of sites');
    netcdf.putAtt(ncid,IDVarId2,'units','degrees east');

    IDVarId3 = netcdf.defVar(ncid,'lat','double',[siteCount]);
    netcdf.putAtt(ncid,IDVarId3,'standardName','latitude');
    netcdf.putAtt(ncid,IDVarId3,'longName','latitude of sites');
    netcdf.putAtt(ncid,IDVarId3,'units','degrees north');

    IDVarId4 = netcdf.defVar(ncid,'time','double',[nDates]);
    netcdf.putAtt(ncid,IDVarId4,'standardName','startDay');
    netcdf.putAtt(ncid,IDVarId4,'longName','start date of simulation Modified Julian dy');
    netcdf.putAtt(ncid,IDVarId4,'longName','start date in Modified Julian Days (days since 1858-11-17 00:00:00)');
    netcdf.putAtt(ncid,IDVarId4,'units','UTC');

    IDVarId5 = netcdf.defVar(ncid,'Times','char',[nDates dateLength]);
    netcdf.putAtt(ncid,IDVarId5,'standardName','startDate');
    netcdf.putAtt(ncid,IDVarId5,'longName','start date of simulation YYYY-MM-DD');
    netcdf.putAtt(ncid,IDVarId5,'units','UTC');

    IDVarId6 = netcdf.defVar(ncid,'c','double',[nConnections three]);
    netcdf.putAtt(ncid,IDVarId6,'standardName','connectivity');
    netcdf.putAtt(ncid,IDVarId6,'longName','larval connectivity of sites');
    netcdf.putAtt(ncid,IDVarId6,'units','probability');
    netcdf.putAtt(ncid,IDVarId6,'description','source, destination, connectivity');

    % IDVarId6 = netcdf.defVar(ncid,'c','double',[siteCount siteCount nDates]);
    % netcdf.putAtt(ncid,IDVarId6,'standardName','connectivity');
    % netcdf.putAtt(ncid,IDVarId6,'longName','larval connectivity of sites');
    % netcdf.putAtt(ncid,IDVarId6,'units','probability');
    % netcdf.putAtt(ncid,IDVarId6,'description','source X destination X startDate');

    IDVarId7 = netcdf.defVar(ncid,'nS','double',[siteCount]);
    netcdf.putAtt(ncid,IDVarId7,'standardName','nSources');
    netcdf.putAtt(ncid,IDVarId7,'longName','number of source sites');
    netcdf.putAtt(ncid,IDVarId7,'units','count');
    netcdf.putAtt(ncid,IDVarId7,'description','count of source sites for each site');

    IDVarId8 = netcdf.defVar(ncid,'nD','double',[siteCount]);
    netcdf.putAtt(ncid,IDVarId8,'standardName','nDestinations');
    netcdf.putAtt(ncid,IDVarId8,'longName','number of destination sites');
    netcdf.putAtt(ncid,IDVarId8,'units','count');
    netcdf.putAtt(ncid,IDVarId8,'description','count of destination sites for each site');

    IDVarId9 = netcdf.defVar(ncid,'sS','double',[siteCount]);
    netcdf.putAtt(ncid,IDVarId9,'standardName','sumSources');
    netcdf.putAtt(ncid,IDVarId9,'longName','sum of source connectivity');
    netcdf.putAtt(ncid,IDVarId9,'units','sum(probability)');
    netcdf.putAtt(ncid,IDVarId9,'description','sum of source connectivity probabilities for each site (can be >1)');

    IDVarId10 = netcdf.defVar(ncid,'sD','double',[siteCount]);
    netcdf.putAtt(ncid,IDVarId10,'standardName','sumDestinations');
    netcdf.putAtt(ncid,IDVarId10,'longName','sum of destination connectivity');
    netcdf.putAtt(ncid,IDVarId10,'units','probability');
    netcdf.putAtt(ncid,IDVarId10,'description','sum of destination connectivity probabilities for each site');

    netcdf.endDef(ncid);

    netcdf.putVar(ncid,IDVarId1,siteNames);
    netcdf.putVar(ncid,IDVarId2,siteLon);
    netcdf.putVar(ncid,IDVarId3,siteLat);
    netcdf.putVar(ncid,IDVarId4,modJulDay);
    netcdf.putVar(ncid,IDVarId5,startDates);
    %netcdf.putVar(ncid,IDVarId6,connectivity);
    netcdf.putVar(ncid,IDVarId6,connectTable);

    netcdf.putVar(ncid,IDVarId7,nSources);
    netcdf.putVar(ncid,IDVarId8,nDestinations);
    netcdf.putVar(ncid,IDVarId9,sumSources);
    netcdf.putVar(ncid,IDVarId10,sumDestinations);

    netcdf.close(ncid);

end

%% Check file
% file='C:\Users\sa01ta\Documents\COMPASS\COMPASS_connectivity_testSpecies.nc';
% ncdisp(file)
% 
% c=ncread(file,'c');
% nS=ncread(file,'nS');
% nD=ncread(file,'nD');
% sS=ncread(file,'sS');
% sD=ncread(file,'sD');


